### ISSUE TITLE
Unclear Example Name

### ISSUE THREAD

**Issue by yono38** [americanexpress/parrot#1]
I wanted to start by saying congratulations on open sourcing this Amex team!

I think it would be nice to have a clearer name for the example application than `create-react-app`. Something like `ship-example-app`. This would make it more distinctive if others want to contribute additional examples in the future.

**Comment by crosscompile** [comment]
Thanks @yono38!  I agree `create-react-app` is a little confusing as an example name, merged #2 to use `pirate-ship-app` instead.
