### ISSUE TITLE
Sync project with internal repo

### ISSUE THREAD

**Issue by jgolden17** [americanexpress/parrot#12]
This project has become out of sync with our internal repository.  We will need to force push any updates to this project and release a breaking change.

**Comment by doodirock** [comment]
Great to know @jgolden17 

My question would be:  Do you think it is best to wait for internal to sync before taking up the mantel to battle test and offer suggestions/fixes from our team.  

I don't want to muddy up any public areas with issues if they're already fixed internally.  Thoughts?

**Comment by jgolden17** [comment]
No need, please procede.  I've done the diff on the two repos and don't see any reason we should have conflicts.

**Comment by doodirock** [comment]
Fantastic. Thanks for the heads up.
