### ISSUE TITLE
parrot-middleware: Enhance documentation

### ISSUE THREAD

**Issue by jgolden17** [americanexpress/parrot#15]
- [x] Add new branding
- [ ] Document API endpoints. These should include usage examples that illustrate the request and response bodies

**Comment by amexjake** [comment]
I'll pick up this one. Adding some examples should be straightforward, but where is the new branding? Just what's in the root of the project?

**Comment by jgolden17** [comment]
Branding is actually done already. It was completed along with the main repo README
