### ISSUE TITLE
Parrot extension disappears

### ISSUE THREAD

**Issue by cyrusxs** [americanexpress/parrot#19]
I unfortunately don't know what causes this, and I haven't been able to recreate it, however I used to have the Parrot extension added to my Chrome browser, and it was showing in my list of extensions.

However, when I opened up the Chrome dev tools, I couldn't see the Parrot tab. After rebooting, I went into the Chrome extensions section and found that the extension had disappeared. I think perhaps it uninstalled itself? It may occur when Chrome updates itself, but this is purely a guess.

**Comment by JamesSingleton** [comment]
I personally have seen this happen when Chrome updates for some reason, not sure if it is something that Chrome does to extensions installed outside of the extensions store or not.

**Comment by jgolden17** [comment]
Chrome removes any extensions that weren't installed via the Chrome Store.  This is an old post from the Chrome team, but i believe it is still applicable:  https://support.google.com/chrome/forum/AAAAP1KN0B0d35tIyH8dVM/?hl=en&gpf=%23!msg%2Fchrome%2Fd35tIyH8dVM%2FUGj_iga3x8UJ&msgid=UGj_iga3x8UJ

**Comment by jgolden17** [comment]
We have published the extension to the [Chrome Web Store](https://chrome.google.com/webstore/detail/parrot-devtools/jckchajdleibnohnphddbiglgpjpbffn?hl=en&gl=US&authuser=1).  If you install from the store, Chrome should no longer remove the extension when updating.
