### ISSUE TITLE
parrot-devtools: Update Readme to reflect Chrome Web Store installation

### ISSUE THREAD

**Issue by jgolden17** [americanexpress/parrot#26]
The Readme should provide a link to the Parrot DevTools extension within the Chrome Web Store.  Instructions for installing from the zip file should be retained but should come under a **Development** heading.

**Comment by amexjake** [comment]
#24 needs to be done before this can be worked

**Comment by jgolden17** [comment]
Closed 24.  Already have a PR for this. Need to get better about tagging issues in my PRs
